name = "hinoto_cli"
version = "0.0.1"
target = "javascript"

description = "Setup tools for Hinoto."
licences = ["MIT"]
repository = { type = "github", user = "Comamoca", repo = "hinoto_cli" }
links = [{ title = "Hinoto", href = "https://github.com/Comamoca/hinoto" }]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
simplifile = ">= 2.3.0 and < 3.0.0"
tom = ">= 2.0.0 and < 3.0.0"
snag = ">= 1.1.0 and < 2.0.0"
handles = ">= 5.0.0 and < 6.0.0"
clip = ">= 1.0.0 and < 2.0.0"
argv = ">= 1.0.2 and < 2.0.0"
shellout = ">= 1.7.0 and < 2.0.0"
gleam_community_ansi = ">= 1.4.3 and < 2.0.0"
filepath = ">= 1.1.0 and < 2.0.0"
gleam_javascript = ">= 1.0.0 and < 2.0.0"


[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
gleam_hexpm = ">= 3.0.1 and < 4.0.0"
